name: sf_building_complaints
channels:
  - defaults
dependencies:
  - pip=21.2.4
  - python=3.9.5
  - pip:
      - ipykernel==6.4.1
      - jupyter_nbextensions_configurator==0.4.1
      - matplotlib==3.4.3
      - notebook==6.4.3
      - numpy==1.21.2
      - pandas==1.3.2
      - scikit-learn==0.24.2
      - seaborn==0.11.2
      - sodapy==2.1.0
