name: sf_building_complaints
channels:
  - conda-forge
  - defaults
dependencies:
  - imbalanced-learn=0.8.0
  - inflect=5.3.0
  - ipykernel=6.4.1
  - ipython=7.27.0
  - ipywidgets=7.6.3
  - jsonschema=3.2.0
  - jupyter_client=7.0.1
  - jupyter_contrib_core=0.3.3
  - jupyter_core=4.7.1
  - jupyter_nbextensions_configurator=0.4.1
  - jupyterlab_pygments=0.1.2
  - matplotlib=3.4.3
  - nb_conda_kernels=2.3.1
  - notebook=6.4.4
  - numpy=1.19.5
  - pandas=1.3.2
  - pickleshare=0.7.5
  - pip=21.2.4
  - python=3.9.5
  - sagemaker-python-sdk=2.59.1
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - seaborn=0.11.2
  - spacy=3.1.3
  - tqdm=4.62.3
  - wordcloud=1.8.1
  - pip:
    - keras==2.6.0
    - keras-preprocessing==1.1.2
    - nbclient==0.5.4
    - nltk==3.6.3
    - sodapy==2.1.0
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.6.0
    - tensorflow-addons==0.14.0
    - tensorflow-estimator==2.6.0

